"""empty message

Revision ID: 041c479ab990
Revises: fb74f51a35bb
Create Date: 2024-02-20 21:35:57.608843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c479ab990'
down_revision = 'fb74f51a35bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=125), nullable=False),
    sa.Column('end_time', sa.String(length=125), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_time'),
    sa.UniqueConstraint('start_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_periods')
    # ### end Alembic commands ###
