"""empty message

Revision ID: 0b352280b044
Revises: 4b7c55e3a7f2
Create Date: 2024-04-04 13:43:07.648579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b352280b044'
down_revision = '4b7c55e3a7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('dob', ['dob'], unique=True)

    # ### end Alembic commands ###
