"""empty message

Revision ID: 0f8cc1d7acdc
Revises: 3fb0e1be481e
Create Date: 2024-03-24 23:13:07.997461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8cc1d7acdc'
down_revision = '3fb0e1be481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index('brand_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.create_index('brand_name', ['brand_name'], unique=True)

    # ### end Alembic commands ###
