"""empty message

Revision ID: 12368612a5b1
Revises: e0ae358bd9f9
Create Date: 2024-07-21 11:47:57.777281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12368612a5b1'
down_revision = 'e0ae358bd9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'axis', ['axis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
