"""empty message

Revision ID: 13980cbe16ee
Revises: 05363a91a359
Create Date: 2024-07-14 13:48:40.873831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13980cbe16ee'
down_revision = '05363a91a359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'axis', ['axis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
