"""empty message

Revision ID: 156d0afd6e67
Revises: 18db8d98aa27
Create Date: 2024-03-24 23:35:35.713797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156d0afd6e67'
down_revision = '18db8d98aa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_constraint('drugs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit_of_measurements', ['uom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drugs_ibfk_1', 'drug_category', ['uom_id'], ['id'])

    # ### end Alembic commands ###
