"""empty message

Revision ID: 18db8d98aa27
Revises: 0f8cc1d7acdc
Create Date: 2024-03-24 23:25:24.985496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db8d98aa27'
down_revision = '0f8cc1d7acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drug_category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('drugs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_category', ['uom_id'], ['id'])
        batch_op.create_foreign_key(None, 'drug_category', ['drug_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drugs_ibfk_1', 'unit_of_measurements', ['uom_id'], ['id'])
        batch_op.drop_column('drug_category_id')

    # ### end Alembic commands ###
