"""empty message

Revision ID: 19bf29078fc9
Revises: 8182cc0888b3
Create Date: 2024-03-01 22:42:06.506720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19bf29078fc9'
down_revision = '8182cc0888b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_constraint('scheduling_ibfk_2', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('scheduling_ibfk_2', 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###
