"""empty message

Revision ID: 246b6679bf8e
Revises: d8eae8e86db1
Create Date: 2024-08-05 16:43:04.050222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '246b6679bf8e'
down_revision = 'd8eae8e86db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'drugs', ['drug_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
