"""empty message

Revision ID: 25cfe05f90f3
Revises: 2ec4c2ff4f42
Create Date: 2024-08-05 14:53:47.993546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cfe05f90f3'
down_revision = '2ec4c2ff4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
