"""empty message

Revision ID: 28c595481312
Revises: b1c9de54ec6d
Create Date: 2024-07-02 23:58:55.644276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28c595481312'
down_revision = 'b1c9de54ec6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_comment', sa.String(length=425), nullable=True))
        batch_op.alter_column('reviewed_by',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=425),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=425),
               nullable=False)
        batch_op.alter_column('reviewed_by',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.drop_column('reviewer_comment')

    # ### end Alembic commands ###
