"""empty message

Revision ID: 2dad75901900
Revises: 87af48e11272
Create Date: 2024-07-13 12:22:20.572433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dad75901900'
down_revision = '87af48e11272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('suite_unit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'axis', ['axis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('logo_path')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('suite_unit')
        batch_op.drop_column('street_address')
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###
