"""empty message

Revision ID: 2ec4c2ff4f42
Revises: da999edecd99
Create Date: 2024-08-04 06:26:34.850383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec4c2ff4f42'
down_revision = 'da999edecd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'participants', ['participant_id'], ['id'])
        batch_op.create_foreign_key(None, 'prescriptions', ['mar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
