"""empty message

Revision ID: 340b706519cc
Revises: 723a1d49b38a
Create Date: 2024-07-30 09:29:54.412067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340b706519cc'
down_revision = '723a1d49b38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'axis', ['axis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
