"""empty message

Revision ID: 3a5dfb87c248
Revises: 88da4fbc485e
Create Date: 2024-07-18 15:07:38.763858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a5dfb87c248'
down_revision = '88da4fbc485e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_address', sa.String(length=100), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_two')
        batch_op.drop_column('address_line_one')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('address_line_one', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('address_line_two', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('home_address')

    op.drop_table('document_types')
    # ### end Alembic commands ###
