"""empty message

Revision ID: 3c34a20bbf8a
Revises: 30ffaac27261
Create Date: 2024-06-10 21:24:04.226323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c34a20bbf8a'
down_revision = '30ffaac27261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_constraint('daily_notes_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_foreign_key('daily_notes_ibfk_3', 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###
