"""empty message

Revision ID: 3e9a9977aff4
Revises: 5232793c6b81
Create Date: 2024-03-22 22:04:00.972066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9a9977aff4'
down_revision = '5232793c6b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_service_history', schema=None) as batch_op:
        batch_op.drop_index('service_type_id')
        batch_op.create_foreign_key(None, 'users', ['service_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_service_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('service_type_id', ['service_type_id'], unique=True)

    # ### end Alembic commands ###
