"""empty message

Revision ID: 3fb0e1be481e
Revises: 72f4e095bbc3
Create Date: 2024-03-24 22:59:55.235126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb0e1be481e'
down_revision = '72f4e095bbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_category_name', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_category_name')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=125), nullable=False),
    sa.Column('brand_name', sa.String(length=125), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uom_id'], ['unit_of_measurements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name'),
    sa.UniqueConstraint('drug_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs')
    op.drop_table('drug_category')
    # ### end Alembic commands ###
