"""empty message

Revision ID: 3fff9a2e9228
Revises: 92de7afa2423
Create Date: 2024-03-22 23:52:53.345173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fff9a2e9228'
down_revision = '92de7afa2423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mit_name', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mit_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mit')
    # ### end Alembic commands ###
