"""empty message

Revision ID: 40eafc9f77d7
Revises: 16bc06fdb6f1
Create Date: 2024-06-09 14:40:56.213010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40eafc9f77d7'
down_revision = '16bc06fdb6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=425), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_notes')
    # ### end Alembic commands ###
