"""empty message

Revision ID: 4109097f85f9
Revises: 464b88672591
Create Date: 2024-07-28 17:10:24.521424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4109097f85f9'
down_revision = '464b88672591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_action_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('med_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mar_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('administered_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mar_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['med_action_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med_actions')
    op.drop_table('med_action_statuses')
    # ### end Alembic commands ###
