"""empty message

Revision ID: 48662515658f
Revises: 7e9e5bc882ac
Create Date: 2024-01-21 14:32:57.551805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48662515658f'
down_revision = '7e9e5bc882ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio_name', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio_name')
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genders')
    op.drop_table('bio_titles')
    # ### end Alembic commands ###
