"""empty message

Revision ID: 50a4c2ca94b3
Revises: 5bb13ea9df93
Create Date: 2024-08-05 15:53:22.997435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a4c2ca94b3'
down_revision = '5bb13ea9df93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'axis', ['axis_id'], ['id'])

    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.drop_constraint('med_errors_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('med_errors_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.create_foreign_key('med_errors_ibfk_3', 'participants', ['participant_id'], ['id'])
        batch_op.create_foreign_key('med_errors_ibfk_2', 'prescriptions', ['mar_id'], ['id'])

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
