"""empty message

Revision ID: 5608fdf3683e
Revises: a13cf18aadd3
Create Date: 2024-03-24 13:21:01.532391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5608fdf3683e'
down_revision = 'a13cf18aadd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_physician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('physician_name', sa.String(length=55), nullable=False),
    sa.Column('physician_phone', sa.String(length=55), nullable=False),
    sa.Column('physician_address', sa.String(length=155), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physician_address'),
    sa.UniqueConstraint('physician_name'),
    sa.UniqueConstraint('physician_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_physician')
    # ### end Alembic commands ###
