"""empty message

Revision ID: 68c1c8108e44
Revises: c7bd1a8c182d
Create Date: 2024-02-20 21:39:49.840231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c1c8108e44'
down_revision = 'c7bd1a8c182d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.drop_index('end_time')
        batch_op.drop_index('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.create_index('start_time', ['start_time'], unique=True)
        batch_op.create_index('end_time', ['end_time'], unique=True)

    # ### end Alembic commands ###
