"""empty message

Revision ID: 788edb4b1e9d
Revises: bacdd2451e40
Create Date: 2024-03-23 12:01:55.979997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788edb4b1e9d'
down_revision = 'bacdd2451e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cm_name', sa.String(length=55), nullable=False),
    sa.Column('cm_phone', sa.String(length=55), nullable=False),
    sa.Column('cm_emergency_phone', sa.String(length=55), nullable=True),
    sa.Column('cm_address', sa.String(length=225), nullable=False),
    sa.Column('cm_fax', sa.String(length=225), nullable=True),
    sa.Column('cm_email_address', sa.String(length=225), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cm_address'),
    sa.UniqueConstraint('cm_email_address'),
    sa.UniqueConstraint('cm_emergency_phone'),
    sa.UniqueConstraint('cm_fax'),
    sa.UniqueConstraint('cm_name'),
    sa.UniqueConstraint('cm_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_manager')
    # ### end Alembic commands ###
