"""empty message

Revision ID: 7ca3cca5953e
Revises: ff9fc1f56416
Create Date: 2024-08-03 12:36:27.830182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca3cca5953e'
down_revision = 'ff9fc1f56416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_error_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('mar_id', sa.Integer(), nullable=False),
    sa.Column('error_reason_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['error_reason_id'], ['med_error_reasons.id'], ),
    sa.ForeignKeyConstraint(['mar_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med_errors')
    op.drop_table('med_error_reasons')
    # ### end Alembic commands ###
