"""empty message

Revision ID: 7fc8ea1843b0
Revises: fc19fd0db20a
Create Date: 2024-03-24 18:25:10.761962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc8ea1843b0'
down_revision = 'fc19fd0db20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_manager', schema=None) as batch_op:
        batch_op.drop_index('cm_address')
        batch_op.drop_index('cm_email_address')
        batch_op.drop_index('cm_emergency_phone')
        batch_op.drop_index('cm_fax')
        batch_op.drop_index('cm_name')
        batch_op.drop_index('cm_phone')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_index('axis_name')

    with op.batch_alter_table('eci', schema=None) as batch_op:
        batch_op.drop_index('gaurdian_address')
        batch_op.drop_index('gaurdian_name')
        batch_op.drop_index('gaurdian_phone')

    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.drop_index('mi_name')

    with op.batch_alter_table('mit', schema=None) as batch_op:
        batch_op.drop_index('mit_name')

    with op.batch_alter_table('participant_physician', schema=None) as batch_op:
        batch_op.drop_index('physician_address')
        batch_op.drop_index('physician_name')
        batch_op.drop_index('physician_phone')

    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.drop_index('provider_address')
        batch_op.drop_index('provider_name')
        batch_op.drop_index('provider_phone')

    with op.batch_alter_table('preferred_hospital', schema=None) as batch_op:
        batch_op.drop_index('ph_address')
        batch_op.drop_index('ph_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferred_hospital', schema=None) as batch_op:
        batch_op.create_index('ph_name', ['ph_name'], unique=True)
        batch_op.create_index('ph_address', ['ph_address'], unique=True)

    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.create_index('provider_phone', ['provider_phone'], unique=True)
        batch_op.create_index('provider_name', ['provider_name'], unique=True)
        batch_op.create_index('provider_address', ['provider_address'], unique=True)

    with op.batch_alter_table('participant_physician', schema=None) as batch_op:
        batch_op.create_index('physician_phone', ['physician_phone'], unique=True)
        batch_op.create_index('physician_name', ['physician_name'], unique=True)
        batch_op.create_index('physician_address', ['physician_address'], unique=True)

    with op.batch_alter_table('mit', schema=None) as batch_op:
        batch_op.create_index('mit_name', ['mit_name'], unique=True)

    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.create_index('mi_name', ['mi_name'], unique=True)

    with op.batch_alter_table('eci', schema=None) as batch_op:
        batch_op.create_index('gaurdian_phone', ['gaurdian_phone'], unique=True)
        batch_op.create_index('gaurdian_name', ['gaurdian_name'], unique=True)
        batch_op.create_index('gaurdian_address', ['gaurdian_address'], unique=True)

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_index('axis_name', ['axis_name'], unique=True)

    with op.batch_alter_table('case_manager', schema=None) as batch_op:
        batch_op.create_index('cm_phone', ['cm_phone'], unique=True)
        batch_op.create_index('cm_name', ['cm_name'], unique=True)
        batch_op.create_index('cm_fax', ['cm_fax'], unique=True)
        batch_op.create_index('cm_emergency_phone', ['cm_emergency_phone'], unique=True)
        batch_op.create_index('cm_email_address', ['cm_email_address'], unique=True)
        batch_op.create_index('cm_address', ['cm_address'], unique=True)

    # ### end Alembic commands ###
