"""empty message

Revision ID: 8182cc0888b3
Revises: 91e5afc48df5
Create Date: 2024-03-01 22:31:59.252103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8182cc0888b3'
down_revision = '91e5afc48df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
