"""empty message

Revision ID: 825cf198743a
Revises: a1acaeaef036
Create Date: 2024-01-26 01:53:27.032447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825cf198743a'
down_revision = 'a1acaeaef036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=120), nullable=False),
    sa.Column('ssn', sa.String(length=15), nullable=False),
    sa.Column('maid_number', sa.String(length=255), nullable=False),
    sa.Column('legal_status', sa.String(length=100), nullable=True),
    sa.Column('home_address', sa.String(length=100), nullable=True),
    sa.Column('home_phone', sa.String(length=100), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('bio_title_id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bio_title_id'], ['bio_titles.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dob')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###
