"""empty message

Revision ID: 85b3f875b14a
Revises: b3e7abb5137f
Create Date: 2024-03-25 00:54:38.233587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b3f875b14a'
down_revision = 'b3e7abb5137f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=12), nullable=False),
    sa.Column('supplier_phone', sa.String(length=12), nullable=True),
    sa.Column('supplier_address', sa.String(length=155), nullable=True),
    sa.Column('supplier_contact_person', sa.String(length=120), nullable=True),
    sa.Column('supplier_balance', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_name'),
    sa.UniqueConstraint('supplier_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    # ### end Alembic commands ###
