"""empty message

Revision ID: 879b518e33e3
Revises: d5bc28f12e49
Create Date: 2024-05-17 09:47:31.891924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '879b518e33e3'
down_revision = 'd5bc28f12e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_received', sa.String(length=12), nullable=False))
        batch_op.alter_column('transaction_code',
               existing_type=mysql.VARCHAR(length=125),
               nullable=True)
        batch_op.drop_column('quatity_received')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quatity_received', mysql.VARCHAR(length=12), nullable=False))
        batch_op.alter_column('transaction_code',
               existing_type=mysql.VARCHAR(length=125),
               nullable=False)
        batch_op.drop_column('quantity_received')

    # ### end Alembic commands ###
