"""empty message

Revision ID: 87af48e11272
Revises: b7f149487c23
Create Date: 2024-07-13 11:34:52.376198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87af48e11272'
down_revision = 'b7f149487c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('suite_unit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('logo_path')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('suite_unit')
        batch_op.drop_column('street_address')
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###
