"""empty message

Revision ID: 8bc4173d5645
Revises: 6dbf9f4c2f39
Create Date: 2024-01-18 04:34:56.386408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc4173d5645'
down_revision = '6dbf9f4c2f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('medical_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_name')
    )
    op.create_table('unit_of_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=45), nullable=False),
    sa.Column('symbol', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol'),
    sa.UniqueConstraint('unit_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_of_measurements')
    op.drop_table('medical_conditions')
    op.drop_table('behavioral_statuses')
    # ### end Alembic commands ###
