"""empty message

Revision ID: 8d0745bf77d8
Revises: 6d68d500f35f
Create Date: 2024-03-22 23:21:46.313755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0745bf77d8'
down_revision = '6d68d500f35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'participants', ['participant_id'], ['id'])

    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'participants', ['participant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
