"""empty message

Revision ID: 91e5afc48df5
Revises: 1206d97a308e
Create Date: 2024-02-28 03:04:09.734338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e5afc48df5'
down_revision = '1206d97a308e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['scheduled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('scheduled_by')

    # ### end Alembic commands ###
