"""empty message

Revision ID: 92de7afa2423
Revises: 5091bce4371a
Create Date: 2024-03-22 23:33:30.093954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92de7afa2423'
down_revision = '5091bce4371a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('axis_name', sa.String(length=12), nullable=False))
        batch_op.drop_index('axis')
        batch_op.create_unique_constraint(None, ['axis_name'])
        batch_op.drop_column('axis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('axis', mysql.VARCHAR(length=12), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('axis', ['axis'], unique=True)
        batch_op.drop_column('axis_name')

    # ### end Alembic commands ###
