"""empty message

Revision ID: a048cf69fbac
Revises: 246b6679bf8e
Create Date: 2024-08-05 17:04:36.063904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a048cf69fbac'
down_revision = '246b6679bf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'participants', ['participant_id'], ['id'])
        batch_op.create_foreign_key(None, 'prescriptions', ['mar_id'], ['id'])
        batch_op.create_foreign_key(None, 'drugs', ['drug_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
