"""empty message

Revision ID: a276541bc3bd
Revises: a620cd3c75f6
Create Date: 2024-03-25 11:06:10.280072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a276541bc3bd'
down_revision = 'a620cd3c75f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_category_name', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_category_name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=12), nullable=False),
    sa.Column('supplier_phone', sa.String(length=12), nullable=True),
    sa.Column('supplier_address', sa.String(length=155), nullable=True),
    sa.Column('supplier_contact_person', sa.String(length=120), nullable=True),
    sa.Column('supplier_balance', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_name'),
    sa.UniqueConstraint('supplier_phone')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_category_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=125), nullable=False),
    sa.Column('generic_name', sa.String(length=125), nullable=False),
    sa.Column('brand_name', sa.String(length=125), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_category_id'], ['drug_category.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['unit_of_measurements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_name')
    )
    op.create_table('batch_num_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_num', sa.String(length=125), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_condition_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_condition_id'], ['medical_conditions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_condition_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_condition_id'], ['medical_conditions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=125), nullable=False),
    sa.Column('batch_code', sa.String(length=125), nullable=False),
    sa.Column('quatity_received', sa.String(length=12), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.String(length=125), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_total')
    op.drop_table('stock')
    op.drop_table('medical_information')
    op.drop_table('diagnosis')
    op.drop_table('batch_num_records')
    op.drop_table('drugs')
    op.drop_table('supplier')
    op.drop_table('drug_category')
    # ### end Alembic commands ###
