"""empty message

Revision ID: a6824131b21f
Revises: 156d0afd6e67
Create Date: 2024-03-24 23:45:18.336901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6824131b21f'
down_revision = '156d0afd6e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generic_name', sa.String(length=125), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('generic_name')

    # ### end Alembic commands ###
