"""empty message

Revision ID: acd4d1a2ea2a
Revises: b4f654e55067
Create Date: 2024-07-09 17:19:37.005785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd4d1a2ea2a'
down_revision = 'b4f654e55067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mar_id', sa.Integer(), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('administered_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mar_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todays_frequency', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('todays_frequency')

    op.drop_table('administrations')
    # ### end Alembic commands ###
