"""empty message

Revision ID: b1c9de54ec6d
Revises: aeb6bbc5ea98
Create Date: 2024-07-02 23:16:39.733106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c9de54ec6d'
down_revision = 'aeb6bbc5ea98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_comment', sa.String(length=425), nullable=True))
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=425),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=425),
               nullable=False)
        batch_op.drop_column('reviewer_comment')

    # ### end Alembic commands ###
