"""empty message

Revision ID: b35dab1e9cfd
Revises: 82dd36c4f59d
Create Date: 2024-03-25 10:38:27.355146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b35dab1e9cfd'
down_revision = '82dd36c4f59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_condition_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'medical_conditions', ['medical_condition_id'], ['id'])
        batch_op.drop_column('axis_name')

    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_condition_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'medical_conditions', ['medical_condition_id'], ['id'])
        batch_op.drop_column('mi_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mi_name', mysql.VARCHAR(length=25), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medical_condition_id')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('axis_name', mysql.VARCHAR(length=12), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medical_condition_id')

    # ### end Alembic commands ###
