"""empty message

Revision ID: b3e7abb5137f
Revises: a6824131b21f
Create Date: 2024-03-25 00:03:05.974829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e7abb5137f'
down_revision = 'a6824131b21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_category_name', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_category_name')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_category_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=125), nullable=False),
    sa.Column('generic_name', sa.String(length=125), nullable=False),
    sa.Column('brand_name', sa.String(length=125), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_category_id'], ['drug_category.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['unit_of_measurements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs')
    op.drop_table('drug_category')
    # ### end Alembic commands ###
