"""empty message

Revision ID: b538c7c18353
Revises: ea3218f68ba6
Create Date: 2024-06-09 22:10:10.565908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b538c7c18353'
down_revision = 'ea3218f68ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_constraint('daily_notes_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_foreign_key('daily_notes_ibfk_3', 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###
