"""empty message

Revision ID: bacdd2451e40
Revises: e36ba5575a17
Create Date: 2024-03-23 01:20:22.109431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacdd2451e40'
down_revision = 'e36ba5575a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gaurdian_name', sa.String(length=55), nullable=False),
    sa.Column('gaurdian_phone', sa.String(length=55), nullable=False),
    sa.Column('gaurdian_address', sa.String(length=225), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gaurdian_address'),
    sa.UniqueConstraint('gaurdian_name'),
    sa.UniqueConstraint('gaurdian_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eci')
    # ### end Alembic commands ###
