"""empty message

Revision ID: bdecbc3d0b27
Revises: 915c8b6db639
Create Date: 2024-03-22 22:23:41.825057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdecbc3d0b27'
down_revision = '915c8b6db639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.drop_constraint('participant_service_provider_history_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['service_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_service_provider_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('participant_service_provider_history_ibfk_2', 'users', ['service_type_id'], ['id'])

    # ### end Alembic commands ###
