"""empty message

Revision ID: c169cb9e76b1
Revises: a297d9a689e0
Create Date: 2024-01-21 16:50:22.794086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c169cb9e76b1'
down_revision = 'a297d9a689e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user_types', ['user_type_id'], ['id'])
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type_id')

    # ### end Alembic commands ###
