"""empty message

Revision ID: c68e87138d70
Revises: b538c7c18353
Create Date: 2024-06-09 22:11:33.440489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68e87138d70'
down_revision = 'b538c7c18353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_index('daily_notes_ibfk_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_index('daily_notes_ibfk_3', ['reviewed_by'], unique=False)

    # ### end Alembic commands ###
