"""empty message

Revision ID: c7bd1a8c182d
Revises: 041c479ab990
Create Date: 2024-02-20 21:38:41.218513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7bd1a8c182d'
down_revision = '041c479ab990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.VARCHAR(length=125),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.VARCHAR(length=125),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=125),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=125),
               existing_nullable=False)

    # ### end Alembic commands ###
