"""empty message

Revision ID: d16026a92987
Revises: e9aed532e274
Create Date: 2024-07-06 17:17:38.981239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16026a92987'
down_revision = 'e9aed532e274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('qty')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
