"""empty message

Revision ID: da999edecd99
Revises: 7ca3cca5953e
Create Date: 2024-08-03 14:06:53.177917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da999edecd99'
down_revision = '7ca3cca5953e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_error_reasons', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drug_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_constraint('med_errors_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('med_errors_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('med_errors_ibfk_4', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_errors', schema=None) as batch_op:
        batch_op.create_foreign_key('med_errors_ibfk_4', 'participants', ['participant_id'], ['id'])
        batch_op.create_foreign_key('med_errors_ibfk_3', 'prescriptions', ['mar_id'], ['id'])
        batch_op.create_foreign_key('med_errors_ibfk_1', 'users', ['created_by'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('comment')
        batch_op.drop_column('qty')
        batch_op.drop_column('drug_id')

    with op.batch_alter_table('med_error_reasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
