"""empty message

Revision ID: dbafadb9efd4
Revises: 209bd8f06754
Create Date: 2024-06-11 09:40:04.294880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbafadb9efd4'
down_revision = '209bd8f06754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.alter_column('reviewed_by',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.drop_constraint('daily_notes_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_foreign_key('daily_notes_ibfk_3', 'users', ['reviewed_by'], ['id'])
        batch_op.alter_column('reviewed_by',
               existing_type=sa.String(length=11),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
