"""empty message

Revision ID: dfadab5fd125
Revises: 879b518e33e3
Create Date: 2024-05-28 05:44:22.453236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfadab5fd125'
down_revision = '879b518e33e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('reason_for_medication', sa.String(length=145), nullable=False),
    sa.Column('mar_date', sa.String(length=24), nullable=False),
    sa.Column('mar_time', sa.String(length=24), nullable=False),
    sa.Column('place_of_mar', sa.String(length=125), nullable=False),
    sa.Column('dossage', sa.String(length=125), nullable=False),
    sa.Column('comment', sa.String(length=125), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason_for_medication')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
