"""empty message

Revision ID: efc7959d2a48
Revises: 40eafc9f77d7
Create Date: 2024-06-09 21:35:18.755376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc7959d2a48'
down_revision = '40eafc9f77d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_from', sa.String(length=24), nullable=False))
        batch_op.add_column(sa.Column('date_to', sa.String(length=24), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('date_to')
        batch_op.drop_column('date_from')

    # ### end Alembic commands ###
